### ISSUE TITLE
Cannot create Maxine image

### ISSUE THREAD

**Issue by benpatsai** [arodchen/MaxSim#1]
Hi,

I run into the following error message when executing script/buildImageC1XProduct.sh using the lastest source code:

`Exception in thread "main" com.sun.max.program.ProgramError: Unexpected Program Error: Class java.lang.Class does not declare field declaredFields`

Did I miss any obvious thing? I use OpenJDK 7 u121 instead of u131 (recommended in the Maxine github repo). Is that the reason?

Thanks,
Po-An

**Comment by arodchen** [comment]
Hi Po-An,

Yes, it is likely to be related to the version of JDK.
MaxSim is based on Maxine 2.0 (with Java SE Development Kit 7u25 from Oracle for Linux x64) and was tested on Ubuntu 14.04 LTS.
Please use JDK 7u25 which you can get [here](http://www.oracle.com/technetwork/java/javase/downloads/java-archive-downloads-javase7-521261.html). 
Thank you for reporting this issue. I will make necessary updates to the wiki and README.

Kind regards,
Andrey

**Comment by benpatsai** [comment]
Hi Andrey,

Thanks for the tip! Oracle JDK 7u25 works. I can produce the image now.

Many thanks,
Po-An
